src/components/dashboard/PlayerInfo.tsx
src/pages/dashboard.tsx

responsive player info fragment of the dashboard. it follows the website styling.  #9

Player info section

---

src/components/dashboard/PlayerStats.tsx
src/pages/dashboard.tsx

Player stats element ready.

---

src/components/dashboard/Highlights.tsx
src/components/dashboard/PlayerCard.tsx
src/components/dashboard/PlayerInfo.tsx
src/components/dashboard/PlayerStats.tsx
src/components/dashboard/Teammates.tsx
src/pages/dashboard.tsx

Dashboard responsive and align.

Dashboard composition

---

.eslintrc
README.md
package.json
yarn.lock

integrated and configured [eslint-config](https://github.com/ijsto/eslint-config), and added to README.

Add and configure Prettier

---

package.json
src/pages/_app.tsx
yarn.lock

Updated _app.tsx file to integrate Google Analytics using nextjs-google-analytics. The Gtag id is saved in an environment variable, which is already loaded into the production server.

Integrated Google Analytics

---

src/components/common/Footer.tsx
src/components/sign-up/SignUpForm.tsx
src/components/terms/PrivacyPolicy.tsx
src/components/terms/TermsOfUse.tsx
src/pages/privacy-policy.tsx
src/pages/terms-of-use.tsx
src/styles/dev..css

Add Privacy Policy and Terms of Use pages

---

src/components/about-us/LookingForward.tsx
src/components/common/BlueButton.tsx
src/components/common/Custom404.tsx
src/components/common/Header.tsx
src/components/common/SocialPopUp.tsx
src/components/dashboard/Highlights.tsx
src/components/dashboard/PlayerInfo.tsx
src/components/dashboard/PlayerStats.tsx
src/components/dashboard/Teammates.tsx
src/components/home/FundraisingReimagined.tsx
src/components/home/LatestNews.tsx
src/components/home/TrustedPartners.tsx
src/components/news-insights/FocusArticle.tsx
src/components/news-insights/NewsInsightsCards.tsx
src/components/news-insights/NewsInsightsLoader.tsx
src/components/sign-up/SignUpForm.tsx
src/components/terms/PrivacyPolicy.tsx
src/components/terms/TermsOfUse.tsx
src/pages/about-us.tsx
src/pages/dashboard.tsx
src/pages/index.tsx
src/pages/news/[slug].js
src/pages/news/index.js
src/pages/sign-up.tsx
src/styles/dev..css
src/styles/globals.css

- Following BEM naming convention for custom classes ([Resource A](https://getbem.com/naming/), [Resource B](https://cssguidelin.es/))
- Naming will generally look like this `block__element--modifier`. Multi-word blocks/elements/modifiers will be split by a single hyphen `-`
- End goal is to be able to read the BEM class name and understand the purpose of this class and where it fits into the broader application
- Note: Tailwind classes continue to be used as-is
- Note: I've also cleaned up a couple custom classes that were not being used along the way

CSS refactoring to follow BEM convention

---

.gitignore

remove dependencies and unused imports. Run depcheck in terminal to see unused dependencies #38

unused dependencies, imports and add lock files to gitignore.

---

src/components/about-us/LookingForward.tsx
src/components/about-us/OurMission.tsx
src/components/about-us/WhoWeAre.tsx
src/components/common/BackToTop.tsx
src/components/common/CommonHero.tsx
src/components/common/Header.tsx
src/components/common/SocialPopUp.tsx
src/components/dashboard/PlayerCard.tsx
src/components/home/BeyondTheNumbers.tsx
src/components/home/FundraisingReimagined.tsx
src/components/home/HeroHomepage.tsx
src/components/home/LatestNews.tsx
src/components/home/OurStrategicAdvisor.tsx
src/components/home/PassiveEngagement.tsx
src/components/home/TrustedPartners.tsx
src/components/news-insights/FocusArticle.tsx
src/components/news-insights/NewsInsightsCards.tsx
src/components/news-insights/TargetArticleContent.tsx
src/components/sign-up/SignUpForm.tsx
src/pages/about-us.tsx
src/pages/index.tsx
src/pages/privacy-policy.tsx
src/pages/sign-up.tsx
src/pages/terms-of-use.tsx

#40.
@pm-moyanor Feel free to suggest your own accessibility changes if you see any.

Accessibility review

---

src/components/common/BackToTop.tsx
src/components/common/ErrorBoundary.tsx
src/components/common/api/Api.tsx
src/components/common/api/ApiHelper.tsx
src/components/news-insights/NewsInsightsCards.tsx
src/components/sign-up/SignUpForm.tsx
src/pages/news/[slug].js
src/pages/news/index.js

Okay, I've included some additional human-readable messages that are currently console logged. We may want to handle those messages differently but wasn't sure what would be best.
I also tried messing around with Error Boundaries (and am uploading a class component for it) but I couldn't get it to properly work when testing it so not sure what's going on there. I'll keep messing with it but so far no dice in figuring out this part.

Error handling review

---

src/components/common/BlueButton.tsx
src/components/common/Header.tsx
src/components/common/SocialPopUp.tsx
src/components/common/api/Api.tsx
src/components/common/api/ApiHelper.tsx
src/components/common/api/ApiUrls.tsx
src/components/contact-us/ContactUsForm.tsx
src/components/home/OurStrategicAdvisor.tsx
src/components/sign-up/SignUpForm.tsx
src/pages/contact-us.tsx
src/styles/dev..css
src/styles/globals.css
src/types/Api.type.ts
src/types/ContactUs.type.ts
src/types/SignUp.type.ts
src/utils/seoConfig.ts

#89 
- This PR is missing the Contact Us button in the footer, but will be adding that in after the footer task is completed

Contact us

---

src/components/common/Footer.tsx

modify footer according to figma

---

package.json
src/components/common/Dashboard404.tsx
src/middleware.tsx
src/pages/dashboard/404.tsx
src/pages/dashboard/vsa-23/[playerId].tsx
src/types/Dashboard.type.ts

#83 
@HectorAgudelo I'm creating a PR with code that handles the dynamic routing for the dashboard. Once you have your dashboard structure up, we can merge the changes into this PR and we should be good to go.

Dashboard dynamic routing

---

src/app/dashboard/vsa-23/[cardId]/page.tsx
src/components/dashboard/HeroBanner.tsx
src/components/dashboard/MatchSummary.tsx
src/components/dashboard/PastMatches.tsx
src/components/dashboard/PastMatchesLayout.tsx
src/components/dashboard/SeasonHighlights.tsx
src/components/dashboard/SeasonSectionLayout.tsx
src/components/dashboard/Teammates.tsx
src/components/dashboard/TopActionReels.tsx

fix banner alignment
adjust sections to mid-screen
margins and spacing between components

banner, layout ,spacing fix

---

package.json
src/app/dashboard/vsa-23/[cardId]/page.tsx
src/app/layout.tsx
src/app/utils/useMediaQuery.tsx
src/components/dashboard/BarChart.tsx
src/components/dashboard/Charts.tsx
src/components/dashboard/HeroBanner.tsx
src/components/dashboard/LatestMatchCard.tsx
src/components/dashboard/LineChart.tsx
src/components/dashboard/MatchSummary.tsx
src/components/dashboard/PastMatches.tsx
src/components/dashboard/PastMatchesLayout.tsx
src/components/dashboard/ProfileCard.tsx
src/components/dashboard/SeasonHighlights.tsx
src/components/dashboard/SeasonSectionLayout.tsx
src/components/dashboard/Teammates.tsx
src/components/dashboard/TopActionReels.tsx
src/types/Dashboard.type.ts
src/types/Player.type.ts
tailwind.config.js
yarn.lock

[#128](https://github.com/AthletiFi/athletifi-website/issues/128)
[#144](https://github.com/AthletiFi/athletifi-website/issues/144)

Adding loading skeletons to dashboard components; Fixed useMediaQuery causing hydration errors

---

package.json
src/app/dashboard/vsa-23/[cardId]/page.tsx
src/components/dashboard/FlipCard.tsx
src/components/dashboard/HeroBanner.tsx
src/components/dashboard/MatchSummary.tsx
src/components/dashboard/NavBar.tsx
src/components/dashboard/PastMatches.tsx
src/components/dashboard/ProfileCard.tsx

stagger animation on past matches list
card flip animation

header and past matches animations

---

src/components/dashboard/FlipCard.tsx
src/components/dashboard/HeroBanner.tsx
src/components/dashboard/MatchSummary.tsx
src/components/dashboard/PastMatches.tsx
src/components/dashboard/ProfileCard.tsx

Fix header and popup card overflow,margins and alignment

Header/popup refactor breakpoints 

---

next.config.js
src/app/api/dashboard/[...cardId]/route.ts
src/app/dashboard/[...cardId]/page.tsx
src/components/dashboard/BarChart.tsx
src/components/dashboard/Charts.tsx
src/components/dashboard/FlipCard.tsx
src/components/dashboard/HeroBanner.tsx
src/components/dashboard/LatestMatchCard.tsx
src/components/dashboard/LineChart.tsx
src/components/dashboard/MatchSummary.tsx
src/components/dashboard/PastMatches.tsx
src/components/dashboard/PastMatchesLayout.tsx
src/components/dashboard/ProfileCard.tsx
src/components/dashboard/SeasonSectionLayout.tsx
src/components/dashboard/Teammates.tsx
src/components/dashboard/TopActionReels.tsx
src/types/Dashboard.type.ts
src/types/Player.type.ts

Data fetch fixes for variable mismatches (banner, profile, latestMatch); add handling of fetched data for teammates

---

package.json
src/app/help-support/page.tsx
src/app/layout.tsx
src/app/settings/page.tsx
yarn.lock

check the font using next font optimization on settings and help pages

next font settings/help

---

src/app/help-support/page.tsx

Quick PR for the following task: #183

feat: link terms and policies pages to Help and Support page

---

src/app/api/dashboard/[...cardId]/route.ts
src/app/dashboard/[...cardId]/page.tsx
src/app/utils/dashboardHelper.ts
src/components/dashboard/BarChart.tsx
src/components/dashboard/Charts.tsx
src/components/dashboard/HeroBanner.tsx
src/components/dashboard/LatestMatchCard.tsx
src/components/dashboard/LineChart.tsx
src/components/dashboard/NavBar.tsx
src/components/dashboard/SeasonSectionLayout.tsx
src/components/user-portal/AccountDetails.tsx
src/components/user-portal/Header.tsx
src/components/user-portal/ManageReferrals.tsx
src/types/Dashboard.type.ts

#135, #159, #161, #162 
Tagged team this with Hector and think we have a good working solution for the unified API endpoint for the dashboard data.
Once the PR is merged, we will deprecate the old lambda functions and API end points in the API Gateway.

Api refactor

---

src/components/user-portal/FAQ.tsx

Incorporate revised and new FAQ entries focusing on user engagement, privacy controls, video content sourcing, and the importance of community feedback. These updates aim to provide clearer guidance, encourage community input, and emphasize features under development for a more informative and interactive user experience.

feat:add updated FAQs to the FAQs component

---

src/app/api/dashboard/[...cardId]/route.ts
src/app/dashboard/[...cardId]/page.tsx
src/components/dashboard/BarChart.tsx
src/components/dashboard/Charts.tsx
src/components/dashboard/DashboardFetchError.tsx
src/components/dashboard/LatestMatchCard.tsx
src/components/dashboard/LineChart.tsx
src/components/dashboard/MatchSummary.tsx
src/components/dashboard/PastMatches.tsx
src/components/dashboard/SeasonHighlights.tsx
src/components/dashboard/SeasonSectionLayout.tsx
src/components/dashboard/Teammates.tsx
src/components/dashboard/TopActionReels.tsx
src/types/Dashboard.type.ts

#167 Creating a new PR with the updated changes:
- Change to friendlier messaging for "no data" messages, change font color to gray
- Add date to X-Axis in Trend Chart
- Display "no data" warning when trend chart has only 1 data point
- Add error handling for missing weather data in "Match Summary" component

Data load errors

---

src/app/help-support/page.tsx
src/components/common/Header.tsx
src/components/user-portal/AccountDetails.tsx
src/components/user-portal/Header.tsx
src/components/user-portal/ManageReferrals.tsx
src/components/user-portal/Notifications.tsx
src/components/user-portal/PortalNav.tsx

#175 Fixed links in side menu; fixed z-index of user-portal side menu vs. main side menu; restricted scrolling when side menu is open

Side menu links

---

next.config.js
src/app/api/dashboard/[...cardId]/route.ts
src/app/news/page.tsx
src/components/common/Footer.tsx
src/components/common/Header.tsx
src/components/dashboard/FlipCard.tsx
src/components/dashboard/LineChart.tsx
src/components/news-insights/NewsInsightsCards.tsx

- Add Suspense component from React in NewsInsightsCards.tsx
- Wrap the main content of NewsInsightsCards component with Suspense
- Provide a fallback UI for the Suspense component
- Update src/app/news/page.tsx to wrap NewsInsightsCards with Suspense
fix: Resolve "Functions cannot be passed directly to Client Components" error
- Remove 'use client' directive and convert NewsInsightsCards to Server Component
- Alternatively, remove useRouter hook and use window.location.href for navigation
chore: Update build output and optimize production build
- Collect page data and generate static pages
- Collect build traces and finalize page optimization
- Display route sizes and First Load JS shared by all pages

feat: Implement Suspense boundary for useSearchParams hook

---

src/app/dashboard/[...cardId]/page.tsx
src/components/dashboard/BarChart.tsx
src/components/dashboard/Charts.tsx
src/components/dashboard/FlipCard.tsx
src/components/dashboard/HeroBanner.tsx
src/components/dashboard/LatestMatchCard.tsx
src/components/dashboard/LineChart.tsx
src/components/dashboard/MatchSummary.tsx
src/components/dashboard/PastMatches.tsx
src/components/dashboard/PastMatchesLayout.tsx
src/components/dashboard/ProfileCard.tsx
src/components/dashboard/SeasonHighlights.tsx
src/components/dashboard/SeasonSectionLayout.tsx
src/components/dashboard/Teammates.tsx
src/components/dashboard/TopActionReels.tsx
src/styles/dev..css

- Alignment and margins in all components
- replace font var with next/font
- Latest match : overflow scroll on descriptions 
- Profile: overflow Bio
- Season layout: adjust margins, reduce height in "empty data"
- past matches: alignment and adjust responsive feature
- popup card: alignment and simple animation
- teammates: styling, 1 column/rox (scroll x and y)
no animations

UI dashboard adjustments

---

src/app/api/addUser/route.ts
src/app/utils/auth/handlePostSignIn.ts

Fixed the API end point for adding a new user to the postgres database to use a POST request instead of a GET request. Lambda function and API Gateway have been updated accordingly

fix: update lambda function to write user data with a POST request

---

src/app/logout/page.tsx
src/components/auth/LoggedOut.tsx
src/components/common/Custom404.tsx
src/components/dashboard/Navbar.tsx
src/styles/dev..css

feat: add logout page and redirect to the logout page on signout

---

amplify/backend/auth/athletifiAuth/cli-inputs.json
src/app/(auth)/layout.tsx
src/app/register/page.tsx
src/app/utils/auth/handlePostSignIn.ts
src/components/auth/AuthClient.tsx
src/states/userStore.ts

This pull request introduces the referral invite functionality and makes several enhancements to the authentication flow in our Next.js application. The main changes include:
1. Referral Invite:
- Added support for preserving the `invite_id` during the OAuth flow with Google and Facebook.
- Modified the `userStore.ts` file to use `atomWithStorage` from Jotai for persisting the `invite_id` in localStorage.
- Updated the `AuthClient` component to access and update the `inviteIdAtom` using the `useAtom` hook.
- Modified the `useUserData` hook to access the `inviteIdAtom` using the `useAtomValue` hook.
- Updated the `handlePostSignIn` function to pass the `inviteId` from the Jotai state.
- Implemented expiration mechanism for the `invite_id` in localStorage, with a default expiration time of …

Implement Referral Invite Functionality and Enhance Authentication Flow

---

src/app/login/page.tsx
src/app/resolve-auth/page.tsx
src/states/userStore.ts

I was able to follow the jotai example with inviteId to add jotai storage to handle the redirect URL. Thanks for doing all the heavy-lifting team!

fix: replace localStorage with Jotai storage

---

src/states/userStore.ts

#261
Removed circular dependency within the useEffect of useUserData

fix: avoid infinite loop on useUserData notification updates

---

src/app/about-us/page.tsx
src/app/contact-us/page.tsx
src/app/not-found.tsx
src/app/page.tsx
src/app/privacy-policy/page.tsx
src/app/sign-up/page.tsx
src/app/terms-of-use/page.tsx
src/app/utils/seoConfig.ts

#259 Okay, I was able to get a test project working by updating the metadata base URL which was I believe was set incorrectly. By applying the correct base location, I'm now expecting openGraph to be able to source the correct image file.

fix: update metadata baseurl path

---

src/app/api/deleteUserRequest/route.ts
src/app/utils/auth/handlePostSignIn.ts
src/components/user-portal/AccountDetails.tsx
src/states/dashboardStore.ts
src/states/userStore.ts
src/types/User.type.ts

Handle delete account

---

src/app/about-us/page.tsx
src/app/contact-us/page.tsx
src/app/layout.tsx
src/app/not-found.tsx
src/app/page.tsx
src/app/privacy-policy/page.tsx
src/app/sign-up/page.tsx
src/app/terms-of-use/page.tsx
src/app/utils/seoConfig.ts

Another round of edits... still nothing seems to change the meta settings.

fix: attempting another round of config changes for SEO

---

src/states/userStore.ts
src/types/User.type.ts

Merging lambda functions and refactoring owned/guest card data into userStore for #297

fix: refactored owned guest cards into a unified lambda function and added data state into userStore

---

src/states/userStore.ts
src/types/User.type.ts

[#297](https://github.com/AthletiFi/athletifi-website/issues/297)

feat: extend api to include invites

---

src/app/utils/dashboardHelper.ts

fix: remap attribute descriptions to headers

---

src/components/common/Header.tsx

Fixing a quick regression on the notifications modal

fix: add notifications modal back into new header nav

---

src/app/(auth)/profile/page.tsx
src/components/dashboard/BarChart.tsx
src/components/dashboard/LatestMatchCard.tsx
src/components/dashboard/LineChart.tsx
src/components/dashboard/MatchSummary.tsx
src/components/dashboard/PastMatches.tsx
src/components/dashboard/PastMatchesLayout.tsx
src/components/dashboard/SeasonHighlights.tsx
src/components/dashboard/SeasonSectionLayout.tsx
src/components/dashboard/Teammates.tsx
src/components/dashboard/TopActionReels.tsx
src/components/user-portal/CardThumbnail.tsx
src/components/user-portal/ManageReferrals.tsx

modify placeholder messages for better ux, 
change 'decline' to 'opt out', 
remove fixed height in season highlights

Ux and placeholders 

---

src/components/auth/AuthClient.tsx

Remove Google OAuth from Auth Client

---

src/components/dashboard/HeroBanner.tsx

#352 
- Note: Button is hidden on phone/mobile screen

feat: add back to profile button from player dashboard

---

src/components/dashboard/LatestMatchCard.tsx
src/components/dashboard/ProfileCard.tsx
src/components/dashboard/TopActionReels.tsx

#370 latest march card: fix conditional, fix score alignment
#369  Profile card: fix conditional rendering 
#368 top action reels: temporarily render only placeholder until real data logic is added

Dashboard conditionals

---

src/app/(auth)/profile/tempCodeRunnerFile.tsx
src/app/logout/page.tsx
src/app/utils/dashboardHelper.ts
src/components/dashboard/HorizontalTimeline.tsx
src/components/dashboard/MatchSummary.tsx
src/components/user-portal/Header.tsx
src/states/dashboardStore.ts
src/states/userStore.ts

There are still some yarn lint `warnings` regarding useEffect dependencies but the `errors` are resolved.

fix: resolve yarn lint errors

---

src/components/dashboard/LatestMatchCard.tsx
src/components/dashboard/MatchSummary.tsx
src/components/dashboard/PastMatchesLayout.tsx
src/components/dashboard/SeasonSectionLayout.tsx
src/components/dashboard/Teammates.tsx
src/components/dashboard/TopActionReels.tsx

- adjust teammates height and text alignment
- render top action reels, opening a modal on timestamp
- change format of time, remove from past matches

Teammates / action reels

---

src/app/qr-code/[id]/page.tsx
src/components/card-redirect/CardRedirect.tsx
src/components/dashboard/HeroBanner.tsx
src/components/dashboard/HorizontalTimeline.tsx
src/components/dashboard/MatchSummary.tsx
src/components/dashboard/SummaryHighlightCard.tsx
src/types/Dashboard.type.ts

#445 Bringing back the PR after adding functionality to redirect conditionally to the login page with the `invite_id` vs. redirecting directly to the player card dashboard.

Qrcode redirect

---

package.json

Updated aws amplify packages to include fixes

update amplify packages to address potential race condition in AWS amplify
